### ISSUE TITLE
Improve JIRA Development links

### ISSUE THREAD

**Issue by maxcanna** [adespresso/monkey-tools#3]
<img width="404" alt="schermata 2016-06-23 alle 19 15 12" src="https://cloud.githubusercontent.com/assets/1881831/16312833/d9f2907e-3976-11e6-8738-60ca5cfe3697.png">

* Make _1 branch_ link open branch (i.e. `https://github.com/adespresso/adespresso/tree/[branch-name]` page directly
* Make _1 pull request_ link open PR page (i.e. `https://github.com/adespresso/adespresso/pull/[pr-number]`) directly
* Make _Create pull request_ (inside _branch_ modal) link open PR creation page with correct branch selected (i.e. `https://github.com/adespresso/adespresso/compare/[branch-name]`)

**Comment by demerzel3** [comment]
What if we replace the entire section with something like the branches page of github?

![schermata 2016-06-23 alle 20 51 28](https://cloud.githubusercontent.com/assets/442835/16316114/2e8874e2-3985-11e6-8751-e2216997a9b3.png)

Would be more meaningful, and can be used for multiple branches as well.
